sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    access-key-id: LTAI5tN8JjgxTpFSAJj9X6Lg
    access-key-secret: J5HcuI3hfva7s6HRfnhnCGlAYknL0c
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-take-out-hbw